---
- name: Add hosts
  hosts: localhost
  gather_facts: false

  tasks:
        
  - name: Add host
    awx.awx.host:
      name: alfonzo
      description: "Local Host Group"
      inventory: "Local Inventory"
      state: present
      variables:
        example_var: 123
