---
- name: Add host to AWX inventory
  hosts: localhost
  vars:
    awx_api_url: "http://nm-awx:30080/api/v2"
    awx_inventory_id: "2"
    new_host_name: "alfonzo"
    new_host_address: "8.8.8.8"

  tasks:
  - name: Get inventory details
    uri:
      url: "{{ awx_api_url }}/inventories/{{ awx_inventory_id }}/"
      method: GET
      user: "{{ awx_username }}"
      password: "{{ awx_password }}"
      validate_certs: no
      status_code: 200
    register: inventory_details

  - name: Add new host
    uri:
      url: "{{ awx_api_url }}/hosts/"
      method: POST
      user: "{{ awx_username }}"
      password: "{{ awx_password }}"
      body_format: json
      body:
        name: "{{ new_host_name }}"
        description: "New host added via Ansible"
        inventory: "{{ inventory_details.json.id }}"
        enabled: true
        variables: {}
        groups: []
        recent_jobs: []
        instance_id: null
        last_job: null
        last_job_host_summary: null
        last_job_failed: false
        last_job_run: null
        last_update: null
        last_job_id: null
        created: null
        modified: null
        last_login: null
        ansible_facts_modified: null
        ansible_macaddress: null
        ansible_machine_id: null
        ansible_machine_type: null
        ansible_python_interpreter: null
        ansible_ssh_host: "{{ new_host_address }}"
      validate_certs: no
      status_code: 201
