---
- name: Add host to AWX inventory
  hosts: localhost
  vars:
    awx_api_url: "http://nm-awx:30080/api/v2"
    awx_inventory_id: "2"
    new_host_name: "alfonzo"
    new_host_address: "8.8.8.8"

  tasks:

  - name: Add new host
    uri:
      url: "{{ awx_api_url }}/inventories/2/hosts/"
      method: POST
      user: "{{ awx_username }}"
      password: "{{ awx_password }}"
      body_format: json
      body:
        name: "{{ new_host_name }}"
        description: "New host added via Ansible"
      validate_certs: no
      status_code: 201
