---        
- name: Add host to inventory in AWX
  hosts: localhost
  gather_facts: False
  vars:
    awx_base_url: http://localhost/api/v2/
    awx_inventory: "Test_Demo"
    awx_host_name: alfonzo
    awx_host_description: My new host
    awx_host_inventory_id: 2
    tower_host: localhost:30080

  tasks:
  
    - name: Collect AWX admin token the hard way!
      delegate_to: 127.0.0.1
         shell: | curl -sku {{ tower_username }}:{{ tower_password }} -H "Content-Type: application/json" -X POST -d '{"description":"Tower CLI", "application":null, "scope":"write"}' http://{{ tower_host }}/api/v2/users/1/personal_tokens/ | jq '.token' | sed -r 's/\"//g'
      register: tower_token
      no_log: True
  
    - name: Add host to AWX inventory
      delegate_to: 127.0.0.1
      awx.awx.tower_host:
        name: "{{ awx_host_name }}"
        description: "{{ awx_host_description }}"
        inventory: "{{ awx_inventory }}"
        state: present
        tower_username: "{{ awx_username }}"
        tower_password: "{{ awx_password }}"
        tower_host: "http://{{ tower_host }}"
        tower_oauthtoken: "{{ tower_token.stdout }}"
        validate_certs: no
