---        
- name: Add host to inventory in AWX
  hosts: localhost
  gather_facts: False

  tasks:
  
    - name: Collect AWX admin token the hard way!
      delegate_to: 127.0.0.1
         shell: curl -u {{ awx_username }}:{{ awx_password }} -H "Content-Type: application/json" -X POST -d '{"name": "{{ awx_host_name }}","description": "LaMa Host","enabled": true,"instance_id": ""}' http://localhost:30080/api/v2/inventories/2/hosts/
      register: curl_result
