---
- name: Add host to inventory in AWX
  hosts: localhost
  gather_facts: False

  tasks:

    - name: Register host in AWX Inventory
      uri:
        url: "http://nm-awx:30080/api/v2/inventories/2/hosts/"
        method: POST
        user: "{{ awx_username }}"
        password: "{{ awx_password }}"
        return_content: true
        force_basic_auth: true
        body:
          name: "{{ awx_host_name }}"
          description: "LaMa Host"
        headers:
          Content-Type: application/json
        body_format: json
      register: reg_awx_inventory
