---
- name: Using localhost
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create a VM
      ec2_instance:
        name: "{{ i_name }}"
        instance_type: "{{ i_type }}"
        image_id: ami-026ed2fc4c278f5c7
        key_name: "{{ i_keypair }}"
        vpc_subnet_id: "{{ i_subnet }}"
        security_group: "{{ i_secgrp }}"
        state: started
        wait_state: True
