---
- hosts: all
  gather_facts: false
  tasks:
    - name: Install FIGlet
      command: "zypper –n install figlet"
      register: shell_out
    - name: Print the output
      debug:
        msg: "{{ shell_out.stdout_lines }}"
        
    - name: Try it out
      command: "FIGlet LaMa Rocks!"
      register: shell_out
    - name: Print the output
      debug:
        msg: "{{ shell_out.stdout_lines }}"


    - name: Remove FIGlet
      command: "zypper –n remove figlet"
